name: ML Model API Automated Evaluation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  setup-build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker-compose build
    
    - name: Start API service
      run: |
        echo "Starting API service..."
        docker-compose up -d
        echo "Waiting for API to be ready..."
        sleep 20
    
    - name: Verify service is running
      run: |
        echo "Verifying service is running..."
        for i in {1..30}; do
          curl -f http://localhost:8000/health && break
          echo "Attempt $i/30: Service not ready yet..."
          sleep 2
        done
    
    - name: Run health check test
      run: |
        echo "Running health check test..."
        curl -X GET http://localhost:8000/health
        echo ""
    
    - name: Test prediction endpoint
      run: |
        echo "Testing prediction endpoint..."
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{
            "feature1": 5.1,
            "feature2": 3.5,
            "feature3": 1.4,
            "feature4": 0.2,
            "feature5": 0.1
          }'
        echo ""
    
    - name: Test input validation
      run: |
        echo "Testing input validation..."
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{
            "feature1": "invalid",
            "feature2": 3.5,
            "feature3": 1.4,
            "feature4": 0.2,
            "feature5": 0.1
          }' || true
        echo ""
    
    - name: Setup Python for tests
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov httpx
    
    - name: Run test suite
      run: |
        echo "Running test suite..."
        python -m pytest tests/ -v --tb=short
    
    - name: Check service still healthy
      run: |
        echo "Verifying service is still healthy..."
        curl -f http://localhost:8000/health
        echo ""
    
    - name: Stop services
      if: always()
      run: |
        echo "Stopping services..."
        docker-compose down -v
    
    - name: Report results
      if: always()
      run: |
        echo "=== Evaluation Complete ==="
        echo "Build Status: ${{ job.status }}"
